ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.challenge.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/yuno_db"
    url = ${?SPRING_DATASOURCE_URL}
    user = "postgres"
    user = ${?SPRING_DATASOURCE_USERNAME}
    password = "password"
    password = ${?SPRING_DATASOURCE_PASSWORD}
}

redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
}
